# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trip and Tech blog
description: "As you may know, or not, this summer (2016) I will intern at Apple, Cupertino, CA. I will write some of my adventures on this blog. I try to write it in English which is not an easy exercise for me. Feel free to correct me :)"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.thomasmorel.io" # the base hostname & protocol for your site
twitter_username: florenttm
github_username:  fthomasmorel

# Build settings
markdown: kramdown
